[tool.poetry]
name = "hann"
version = "0.1.0"
description = "Python environment for the Hann library"
authors = ["Hassan Abedi <hassan.abedi.t@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
poetry-dynamic-versioning = "^1.4.0"
huggingface-hub = "^0.29.3"
