name: Run Tests

on:
  workflow_dispatch:
  schedule: # Run every day at midnight (UTC)
    - cron: '0 0 * * *'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - 'docs/**'
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - 'docs/**'
    tags:
      - 'v*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # Define the Go versions to test against
        go-version: [ "1.21", "1.22", "1.23", "1.24", "1.25", "1.26" ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y make
          make install-deps
        env:
          CI: true
        continue-on-error: false

      - name: Run tests and generate coverage report
        run: |
          make test # Generates a coverage.txt file for Codecov
        continue-on-error: false

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
        continue-on-error: false
